---
title: "Regression"
author: "Yanran"
date: "2020/11/16"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(segmented)
library(splines)
library(Hmisc)
library(rms)
library(mgcv)
library(caret)
library(tidyverse)
library(dplyr)
```

```{r}
dat = dat_raw %>%
  left_join(elixhauser_icd9[,c('stay_id','wscore_vw')], by = c('stay_id'))%>%
  left_join(elixhauser_icd10[,c('stay_id','wscore_vw')], by = c('stay_id'))%>%
  mutate(elix_vws = ifelse(is.na(wscore_vw.x),wscore_vw.y,wscore_vw.x))%>%
  #mutate(elix_vws = ifelse(is.na(elix_vws),999,elix_vws))%>%
  #mutate(elix_vwc = cut(elix_vws,breaks=c(-Inf,-1,0,4,998,Inf)))%>%
  #mutate(elix_vwc = relevel(elix_vwc, ref = 4))%>%
  select(-c("wscore_vw.x"),'wscore_vw.y')%>%
  filter(hr>24)%>% #ha

  
  hr_day*ethnicity
```



```{r}
url <- "http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
data <- read.csv(url, header=FALSE)


###011 
colnames(data) <- c(
  "age",
  "sex",# 0 = female, 1 = male
  "cp", # chest pain
  # 1 = typical angina,
  # 2 = atypical angina,
  # 3 = non-anginal pain,
  # 4 = asymptomatic
  "trestbps", # resting blood pressure (in mm Hg)
  "chol", # serum cholestoral in mg/dl
  "fbs",  # fasting blood sugar if less than 120 mg/dl, 1 = TRUE, 0 = FALSE
  "restecg", # resting electrocardiographic results
  # 1 = normal
  # 2 = having ST-T wave abnormality
  # 3 = showing probable or definite left ventricular hypertrophy
  "thalach", # maximum heart rate achieved
  "exang",   # exercise induced angina, 1 = yes, 0 = no
  "oldpeak", # ST depression induced by exercise relative to rest
  "slope", # the slope of the peak exercise ST segment
  # 1 = upsloping
  # 2 = flat
  # 3 = downsloping
  "ca", # number of major vessels (0-3) colored by fluoroscopy
  "thal", # this is short of thalium heart scan
  # 3 = normal (no cold spots)
  # 6 = fixed defect (cold spots during rest and exercise)
  # 7 = reversible defect (when cold spots only appear during exercise)
  "hd" # (the predicted attribute) - diagnosis of heart disease  心脏病的诊断属性
  # 0 if less than or equal to 50% diameter narrowing
  # 1 if greater than 50% diameter narrowing
)

str(data)


###012 数据预处理

#将分类变量设置为factor，连续型变量为num保持不变，删除缺失值记录。

## 0121 "?"为字符型数据，将"?"转换为NA
data[data == "?"] <- NA

## 0122 将分类变量设置为factor,连续型变量为num保持不变

#  这一步是确保数据能够在程序中被正确识别

data[data$sex == 0,]$sex <- "F"
data[data$sex == 1,]$sex <- "M"
data$sex <- as.factor(data$sex)

data$cp <- as.factor(data$cp)
data$fbs <- as.factor(data$fbs)
data$restecg <- as.factor(data$restecg)
data$exang <- as.factor(data$exang)
data$slope <- as.factor(data$slope)



data$ca <- as.integer(data$ca) #R将"?"认为是字符型，故需要修正为整数型
data$ca <- as.factor(data$ca)  #将整数型改为因子型 

data$thal <- as.integer(data$thal) # "thal"中也有"?",处理同ca
data$thal <- as.factor(data$thal)

## 将hd(heart disease)中的数字（0~4）改成"Healthy" 和"Unhealthy"
data$hd <- ifelse(test=data$hd == 0, yes="Healthy", no="Unhealthy")
data$hd <- as.factor(data$hd) 


str(data) #再次核验数据类型


## 0123 查看NA个数
table(is.na(data))

##展示含有NA的记录
data[!complete.cases(data),]

data <- na.omit(data)

nrow(data)



### 013数据质控

xtabs(~hd+sex, data = data)

xtabs(~hd+cp, data = data)

xtabs(~hd+fbs, data = data)

xtabs(~hd+exang, data = data)

xtabs(~hd+slope, data = data)

xtabs(~hd+ca, data = data)

xtabs(~hd+thal, data = data)

xtabs(~hd+restecg, data = data)



### 02 简单logistic

xtabs(~hd+sex, data = data)

logistic <- glm(hd ~ sex, data = data, family = 'binomial') # binomial-- logistic GLM

summary(logistic) #coeffients


#R2,P

LL.null <- logistic$null.deviance/-2

LL.proposed <- logistic$deviance/-2

R2 <- (LL.null-LL.proposed)/LL.null

P.proposed <- 1- pchisq(2*(LL.proposed - LL.null), df = 1)

P.proposed <- 1 - pchisq((logistic$null.deviance - logistic$deviance), df=1)



#查看logistic回归的预测结果

predicted.data <- data.frame(
  probability.of.hd = logistic$fitted.values,
  sex = data$sex)

str(predicted.data)


#ggplot2

library("ggplot2")

ggplot(data = predicted.data, aes(x = sex, y = probability.of.hd))+
  geom_point(aes(color=sex), size=5) +
  xlab("Sex") +
  ylab("Predicted probability of getting heart disease")

xtabs(~ probability.of.hd + sex, data=predicted.data)

#"hd~."表示使用数据中所有变量

logistic2 <- glm(hd ~ ., data=data, family="binomial")

summary(logistic2)

#
predicted.data2 <- data.frame(
  probability.of.hd2=logistic2$fitted.values,
  hd2=data$hd)

xtabs(~ probability.of.hd2 + hd2, data=predicted.data2)


str(predicted.data2)

#
predicted.data2 <- predicted.data2[
  order(predicted.data2$probability.of.hd2, decreasing=FALSE),]

predicted.data2$rank <- 1:nrow(predicted.data2)

#
ggplot(data=predicted.data2, aes(x=rank, y=probability.of.hd2)) +
  geom_point(aes(color=hd2), alpha=1, shape=4, stroke=2) +
  xlab("Index") +
  ylab("Predicted probability of getting heart disease")

ggsave("heart_disease_probabilities.pdf")

```



```{r}
allpatients.sofa[allpatients.sofa$respiration_24hours == 0,]$respiration_24hours_b <- 0
allpatients.sofa[allpatients.sofa$respiration_24hours != 0,]$respiration_24hours_b <- 1

dat = allpatients.sofa %>%
  mutate(icu_death = ifelse(status == "Alive", 0, 1)) %>%
  mutate(sex = ifelse(gender == "F", 0, 1)) %>%
  mutate(ethnicity=relevel(ethnicity, ref = 'WHITE')) %>%
  mutate(respiration_24hours_b = ifelse(respiration_24hours == 0, 0, 1)) %>%
  mutate(coagulation_24hours_b = ifelse(coagulation_24hours == 0, 0, 1)) %>%
  mutate(liver_24hours_b = ifelse(liver_24hours == 0, 0, 1)) %>%
  mutate(cns_24hours_b = ifelse(cns_24hours == 0, 0, 1)) %>%
  mutate(renal_24hours_b = ifelse(renal_24hours == 0, 0, 1)) %>%
  mutate(age_div10 = as.integer(anchor_age/10)) 

#allpatients.sofa$sex <- as.integer(allpatients.sofa$gender) - 1
logistic <- glm(icu_death ~ age_div10 + sex + as.factor(ethnicity) + respiration_24hours_b + coagulation_24hours_b + liver_24hours_b + cns_24hours_b + renal_24hours_b + U_sepsis, data = dat, family = 'binomial') # binomial-- logistic GLM

logistic_1 <- glm(icu_death ~ age_div10 + sex + as.factor(ethnicity) + respiration_24hours + coagulation_24hours + liver_24hours + cns_24hours + renal_24hours + U_sepsis, data = dat, family = 'binomial')

logistic_2 <- glm(icu_death ~ age_div10 + sex + as.factor(ethnicity) + respiration_24hours_b + coagulation_24hours_b + liver_24hours_b*as.factor(ethnicity) + cns_24hours_b + renal_24hours_b*as.factor(ethnicity) + U_sepsis, data = dat, family = 'binomial')

summary(logistic) #coeffients
summary(logistic_1)
summary(logistic_2)

```

```{r}
table1(~age_div10 + sex + respiration_24hours_b + coagulation_24hours_b + liver_24hours_b + cns_24hours_b + renal_24hours_b + U_sepsis| status, data = dat)
```










```{r}
all.regression.24 = all.24 %>%
  mutate(icu_death = ifelse(status == "Alive", 0, 1)) %>%
  mutate(sex = ifelse(gender == "F", 0, 1)) %>%
  mutate(ethnicity=relevel(ethnicity, ref = 'WHITE')) %>%
  mutate(respiration_24hours_b = ifelse(respiration_24hours == 0, 0, 1)) %>%
  mutate(coagulation_24hours_b = ifelse(coagulation_24hours == 0, 0, 1)) %>%
  mutate(liver_24hours_b = ifelse(liver_24hours == 0, 0, 1)) %>%
  mutate(cns_24hours_b = ifelse(cns_24hours == 0, 0, 1)) %>%
  mutate(renal_24hours_b = ifelse(renal_24hours == 0, 0, 1)) %>%
  mutate(age_div10 = as.integer(anchor_age/10)) 
logistic.24 <- glm(icu_death ~ age_div10 + sex + as.factor(ethnicity) + respiration_24hours_b + coagulation_24hours_b + liver_24hours_b + cns_24hours_b + renal_24hours_b + U_sepsis, data = all.regression.24, family = 'binomial') 
summary(logistic.24) #coeffients

all.regression.48 = all.48 %>%
  mutate(icu_death = ifelse(status == "Alive", 0, 1)) %>%
  mutate(sex = ifelse(gender == "F", 0, 1)) %>%
  mutate(ethnicity=relevel(ethnicity, ref = 'WHITE')) %>%
  mutate(respiration_24hours_b = ifelse(respiration_24hours == 0, 0, 1)) %>%
  mutate(coagulation_24hours_b = ifelse(coagulation_24hours == 0, 0, 1)) %>%
  mutate(liver_24hours_b = ifelse(liver_24hours == 0, 0, 1)) %>%
  mutate(cns_24hours_b = ifelse(cns_24hours == 0, 0, 1)) %>%
  mutate(renal_24hours_b = ifelse(renal_24hours == 0, 0, 1)) %>%
  mutate(age_div10 = as.integer(anchor_age/10)) 
logistic.48 <- glm(icu_death ~ age_div10 + sex + as.factor(ethnicity) + respiration_24hours_b + coagulation_24hours_b + liver_24hours_b + cns_24hours_b + renal_24hours_b + U_sepsis, data = all.regression.48, family = 'binomial') 
summary(logistic.48)

all.regression.72 = all.72 %>%
  mutate(icu_death = ifelse(status == "Alive", 0, 1)) %>%
  mutate(sex = ifelse(gender == "F", 0, 1)) %>%
  mutate(ethnicity=relevel(ethnicity, ref = 'WHITE')) %>%
  mutate(respiration_24hours_b = ifelse(respiration_24hours == 0, 0, 1)) %>%
  mutate(coagulation_24hours_b = ifelse(coagulation_24hours == 0, 0, 1)) %>%
  mutate(liver_24hours_b = ifelse(liver_24hours == 0, 0, 1)) %>%
  mutate(cns_24hours_b = ifelse(cns_24hours == 0, 0, 1)) %>%
  mutate(renal_24hours_b = ifelse(renal_24hours == 0, 0, 1)) %>%
  mutate(age_div10 = as.integer(anchor_age/10)) 
logistic.72 <- glm(icu_death ~ age_div10 + sex + as.factor(ethnicity) + respiration_24hours_b + coagulation_24hours_b + liver_24hours_b + cns_24hours_b + renal_24hours_b + U_sepsis, data = all.regression.72, family = 'binomial') 
summary(logistic.72)


df1 <- data.frame(coef.24=coef(logistic.24),p.24=summary(logistic.24)$coefficients[,4],
                  coef.48=coef(logistic.48),p.48=summary(logistic.48)$coefficients[,4],
                  coef.72=coef(logistic.72), p.72=summary(logistic.72)$coefficients[,4])
df1
write.csv(df1,'./regression_model/compare3d_reg.csv')
```


